### ISSUE TITLE
Install from Bower

### ISSUE THREAD

**Issue by k010** [turn/Smart-Table#22]
Hi, I saw that you create a bower.json but this fork doesn't have registry in bower.io 
Can you [register](http://bower.io/docs/creating-packages/#register) please, so it can be available install from bower ??

Thanks nice work !!

**Comment by bcherny** [comment]
Glad you like it! Note that this is a forked version of Smart-Table. The original *is* on bower:

```bash
$ bower search smart-table
Search results:

    angular-smart-table git://github.com/lorenzofox3/Smart-Table.git
    smart-table git://github.com/lorenzofox3/bower-smart-table.git
    nr-smart-table git://github.com/nickradford/Smart-Table.git
    smart-table-wix git://github.com/flyingjamus/Smart-Table.git
    aeh-Smart-Table git://github.com/aeharding/Smart-Table.git
```

Additionally, you can install this fork using bower already:

```bash
bower install turn/Smart-Table
```

As far as publishing this fork to the bower registry, that's up to the maintainers. @2013gang @hustcscw

**Comment by k010** [comment]
Good one :+1:  
Thanks !!
